CREATE DATABASE IF NOT EXISTS gestao_pessoas;
USE gestao_pessoas;

CREATE TABLE IF NOT EXISTS pessoas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    idade INT NOT NULL,
    data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP
)